### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by leoTiGRiS** [MarkKoz/ReactBot#2]
So as you told me I updated python to 3.7 but it still drops me another error
![image](https://user-images.githubusercontent.com/44180995/55554717-24bac000-56ec-11e9-89fc-604d12ee7a1f.png)

**Comment by MarkKoz** [comment]
You'll need to install the required packages again since you updated Python.

**Comment by leoTiGRiS** [comment]
Now after installing packages scrypt finally launched but whenever I put a message it drops me this
![image](https://user-images.githubusercontent.com/44180995/55555404-e32b1480-56ed-11e9-942d-25db989d7db1.png)

**Comment by MarkKoz** [comment]
Looks like you have the wrong version of discord.py installed. Try installing it with 

```bash
pip install -U https://github.com/Rapptz/discord.py/archive/async.zip
```

**Comment by leoTiGRiS** [comment]
![image](https://user-images.githubusercontent.com/44180995/55556169-95afa700-56ef-11e9-87c6-b78b7c2b584d.png)

**Comment by leoTiGRiS** [comment]
(after installing through your command)

**Comment by MarkKoz** [comment]
This program is relatively old so it uses an older version of the discord.py package which was released before Python 3.7 was released. 3.7 introduced a breaking change which is causing this syntax error.

I won't bore you with more details. The simplest solution is to downgrade Python to version 3.6. Ideally I would update this program to use the newer version of the discord.py package but my focus is elsewhere at the moment.

**Comment by leoTiGRiS** [comment]
Thank you.

**Comment by leoTiGRiS** [comment]
Sorry do disturb you again. But I changed my python version to 3.6, and it seems like it've worked. But I'm getting this. What kind of emoji code should I put in config otherwise?
![image](https://user-images.githubusercontent.com/44180995/55558851-a105d100-56f5-11e9-92a3-035586ec1dd8.png)

**Comment by MarkKoz** [comment]
It's case sensitive. [Here](https://github.com/carpedm20/emoji/blob/master/emoji/unicode_codes.py#L236) is the full list of aliases the library supports (as the readme states, they don't necessarily correspond to Discord's aliases).

**Comment by leoTiGRiS** [comment]
Gotcha. Works already. Thank you
